version: '2'
services:
  web:
    build:
      context: ./docker/nginx
    links:
      - php
      - db
      - redis
    volumes_from:
      - appdata
#      - logs
    environment:
      - VIRTUAL_HOST=m2.docker
      - PHP_IDE_CONFIG="serverName=localhost"

  appdata:
    image: tianon/true
    volumes:
      - ".:/var/www/html"

  php:
    build:
      context: ./docker/php
    links:
      - db
      - redis
    volumes_from:
      - appdata
    environment:
      -PHP_IDE_CONFIG="serverName=localhost"

  db:
    image: mariadb:latest
    volumes:
      - "/var/lib/mysql"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  redis:
    image: redis
    expose:
      - "6379"

  logs:
    image: tianon/true
    volumes:
      - /var/log/nginx
      - /var/lib/elasticsearch

  elk:
    image: willdurand/elk
    volumes:
      - ./docker/elk/logstash:/etc/logstash
      - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - appdata
      - logs
    environment:
      - VIRTUAL_HOST=logs.docker

  mail:
    image: helder/mailcatcher
    environment:
      - VIRTUAL_HOST=mail.docker


networks:
  default:
    external:
      name: dev