ssl:
  build: ./docker/ssl
  links:
    - varnish
  volumes_from:
    - appdata
    - logs
  environment:
    DNSDOCK_ALIAS: m2.docker

varnish:
  build: ./docker/varnish
  links:
    - web
  volumes_from:
    - appdata

web:
  build: ./docker/nginx
  links:
    - php
    - db
    - redis
  volumes_from:
    - appdata
    - logs

appdata:
  image: tianon/true
  volumes:
    - ".:/var/www/html"

php:
  build: ./docker/php
  links:
    - db
    - redis
    - mail
    - logs
    - selenium
  volumes_from:
    - appdata

db:
  image: mariadb:latest
  volumes:
    - "/var/lib/mysql"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

redis:
  image: redis
  expose:
    - "6379"


logs:
  image: tianon/true
  volumes:
    - /var/log/nginx
    - /var/lib/elasticsearch

elk:
  image: willdurand/elk
  volumes:
    - ./docker/elk/logstash:/etc/logstash
    - ./docker/elk/logstash/patterns:/opt/logstash/patterns
  volumes_from:
    - appdata
    - logs

mail:
  image: helder/mailcatcher

selenium:
  image: selenium/standalone-firefox:2.53.1
  expose:
    - "4444"

node:
  build: ./docker/node
  volumes_from:
    - appdata